spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/polixis_interview
    password: admin
  kafka:
    consumer:
      group-id: group_id_1
    bootstrap-servers: localhost:9092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
